server:
  port: 8080

finnhub:
  baseUrl: https://finnhub.io/api/v1
  apiKey: ${FINNHUB_API_KEY}   # set di environment

market:
  symbols: AAPL,MSFT,NVDA,GOOGL
  pollIntervalMs: 5000

spring:
  datasource:
    url: jdbc:h2:file:./data/pt;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true    # opsional: http://localhost:8080/h2-console
